apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-2
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
      - name: my-app-2
        image: 921470052457.dkr.ecr.ap-south-1.amazonaws.com/mvn-app
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: my-app-2
spec:
  selector:
    app: my-app-2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
